"""Provider-neutral model schemas and adapters boundary."""

from tend.llm.models.base import ModelAdapter
from tend.llm.models.messages import (
    AssistantMessage,
    CompactionSummaryContent,
    ContentKind,
    ContentPart,
    DeveloperMessage,
    Message,
    MessageRole,
    SystemMessage,
    TextContent,
    UserMessage,
)
from tend.llm.models.profiles import (
    CapabilityRequirements,
    ContextWindow,
    ContinuationCapabilities,
    InputModality,
    ModelProfile,
    ModelSettingsCapabilities,
    ProfileKey,
    ProviderApi,
    ProviderCompatibility,
    ReasoningCapabilities,
    TokenPricing,
    ToolCapabilities,
    context_tokens_remaining,
    context_usage_ratio,
    get_builtin_profile,
    list_builtin_profile_keys,
    resolve_max_output_tokens,
    select_continuation_strategy,
    validate_capability_requirements,
)
from tend.llm.models.provider import (
    ContinuationStrategy,
    ProviderCompletionStatus,
    ProviderItemKind,
    ProviderItemMetadata,
    ProviderMetadata,
)
from tend.llm.models.reasoning import (
    ReasoningContinuationMetadata,
    ReasoningDisplayPolicy,
    ReasoningEffort,
    ReasoningMetadata,
    ReasoningSettings,
    ReasoningSummary,
    ReasoningSummaryPreference,
)
from tend.llm.models.requests import ModelMessage, ModelRequest, ModelResponse
from tend.llm.models.tools import (
    ToolCall,
    ToolError,
    ToolResult,
    ToolResultMessage,
    model_visible_tool_result_text,
    normalize_tool_arguments,
)

__all__ = (
    "AssistantMessage",
    "CapabilityRequirements",
    "CompactionSummaryContent",
    "ContentKind",
    "ContentPart",
    "ContextWindow",
    "ContinuationCapabilities",
    "ContinuationStrategy",
    "DeveloperMessage",
    "Message",
    "MessageRole",
    "InputModality",
    "ModelAdapter",
    "ModelMessage",
    "ModelProfile",
    "ModelRequest",
    "ModelResponse",
    "ModelSettingsCapabilities",
    "ProfileKey",
    "ProviderApi",
    "ProviderCompatibility",
    "ProviderCompletionStatus",
    "ProviderItemKind",
    "ProviderItemMetadata",
    "ProviderMetadata",
    "ReasoningCapabilities",
    "ReasoningContinuationMetadata",
    "ReasoningDisplayPolicy",
    "ReasoningEffort",
    "ReasoningMetadata",
    "ReasoningSettings",
    "ReasoningSummary",
    "ReasoningSummaryPreference",
    "SystemMessage",
    "TextContent",
    "TokenPricing",
    "ToolCall",
    "ToolCapabilities",
    "ToolError",
    "ToolResult",
    "ToolResultMessage",
    "UserMessage",
    "context_tokens_remaining",
    "context_usage_ratio",
    "get_builtin_profile",
    "list_builtin_profile_keys",
    "model_visible_tool_result_text",
    "normalize_tool_arguments",
    "resolve_max_output_tokens",
    "select_continuation_strategy",
    "validate_capability_requirements",
)
