"""Usage and cost value types shared across layers."""

from __future__ import annotations

from decimal import Decimal
from typing import Annotated

from pydantic import Field, field_validator

from tend._common.types import StrictModel

_NonNegativeCount = Annotated[int, Field(ge=0)]
_NonNegativeAmount = Annotated[Decimal, Field(ge=Decimal("0"))]


class TokenUsage(StrictModel):
    """Token counts reported by model providers.

    All five token fields are **mutually exclusive and non-overlapping**; none
    of them is a subset of another.  The total context consumed by a request is:

        input_tokens + cache_read_tokens + cache_write_tokens + output_tokens

    Field semantics (Anthropic-native representation, applied uniformly to all
    providers after adapter-layer normalisation):

    * ``input_tokens`` — uncached prompt tokens billed at the full input rate.
      Does *not* include tokens served from or written to the cache.
    * ``cache_read_tokens`` — prompt tokens that were served from an existing
      cache entry.  Additive to ``input_tokens`` for total context; billed at a
      discounted read rate.
    * ``cache_write_tokens`` — prompt tokens written to a new cache entry this
      request (Anthropic 5-minute prompt cache).  Additive; billed at a small
      write surcharge.  Always 0 for providers that do not expose write counts.
    * ``output_tokens`` — tokens generated by the model (assistant turn).
      Includes reasoning tokens on models that reason.
    * ``reasoning_tokens`` — subset of ``output_tokens`` spent on chain-of-
      thought reasoning.  Tracked separately for informational purposes; do
      *not* add it again when totalling cost.

    OpenAI reports ``cached_tokens`` as a *subset* of ``input_tokens``; the
    OpenAI adapter normalises this to the non-overlapping form above before
    surfacing a ``TokenUsage`` to callers.
    """

    input_tokens: _NonNegativeCount = 0
    output_tokens: _NonNegativeCount = 0
    reasoning_tokens: _NonNegativeCount = 0
    cache_read_tokens: _NonNegativeCount = 0
    cache_write_tokens: _NonNegativeCount = 0
    provider_details: dict[str, _NonNegativeCount] = Field(default_factory=dict)

    @field_validator("provider_details")
    @classmethod
    def _validate_provider_detail_keys(cls, details: dict[str, int]) -> dict[str, int]:
        for key in details:
            if not key:
                raise ValueError("provider detail keys must be non-empty")
        return details

    def add(self, other: TokenUsage) -> TokenUsage:
        detail_keys = sorted(self.provider_details.keys() | other.provider_details.keys())
        provider_details = {
            key: self.provider_details.get(key, 0) + other.provider_details.get(key, 0)
            for key in detail_keys
        }
        return TokenUsage(
            input_tokens=self.input_tokens + other.input_tokens,
            output_tokens=self.output_tokens + other.output_tokens,
            reasoning_tokens=self.reasoning_tokens + other.reasoning_tokens,
            cache_read_tokens=self.cache_read_tokens + other.cache_read_tokens,
            cache_write_tokens=self.cache_write_tokens + other.cache_write_tokens,
            provider_details=provider_details,
        )

    def merge(self, other: TokenUsage) -> TokenUsage:
        return self.add(other)


class Cost(StrictModel):
    """Monetary cost when pricing information is configured or reported."""

    amount: _NonNegativeAmount
    currency: str = Field(default="USD", min_length=3, max_length=8)
    pricing_source: str | None = Field(default=None, min_length=1)

    def add(self, other: Cost) -> Cost:
        if self.currency != other.currency:
            raise ValueError("cannot aggregate costs with different currencies")
        pricing_source = (
            self.pricing_source if self.pricing_source == other.pricing_source else "mixed"
        )
        return Cost(
            amount=self.amount + other.amount,
            currency=self.currency,
            pricing_source=pricing_source,
        )

    def merge(self, other: Cost) -> Cost:
        return self.add(other)


class Usage(StrictModel):
    """Aggregate usage counters for a request, turn, session, or compaction."""

    tokens: TokenUsage = Field(default_factory=TokenUsage)
    cost: Cost | None = None
    model_requests: _NonNegativeCount = 0
    retry_attempts: _NonNegativeCount = 0
    tool_calls: _NonNegativeCount = 0

    def add(self, other: Usage) -> Usage:
        return Usage(
            tokens=self.tokens.add(other.tokens),
            cost=_add_optional_cost(self.cost, other.cost),
            model_requests=self.model_requests + other.model_requests,
            retry_attempts=self.retry_attempts + other.retry_attempts,
            tool_calls=self.tool_calls + other.tool_calls,
        )

    def merge(self, other: Usage) -> Usage:
        return self.add(other)


def _add_optional_cost(left: Cost | None, right: Cost | None) -> Cost | None:
    if left is None and right is None:
        return None
    if left is None:
        return right.model_copy(deep=True) if right is not None else None
    if right is None:
        return left.model_copy(deep=True)
    return left.add(right)


__all__ = (
    "Cost",
    "TokenUsage",
    "Usage",
)
